### ISSUE TITLE
Scraping ou API?

### ISSUE THREAD

**Issue by MiguelMA3** [aniltonjunior/simepar-api#1]
Olá, ainda estou começando na área de programação.
Seu projeto faz algum tipo de scraping ou há uma API da simepar? Estou querendo adicionar previsão do tempo em um pequeno projeto pessoal.

Pelo que entendi seu projeto está realizando uma pesquisa diretamente no site da SIMEPAR e retornando os dados. É isso mesmo?

**Comment by aniltonjunior** [comment]
Olá Miguel, tudo bem? 
Esse projeto foi uma tentativa de criar uma API pública, já que não existe uma. Sendo assim, é um ferramente de webscrapping que expõe uma API. 
Contudo não foi pra frente, só tem um recurso e nem sei se funciona atualmente.

**Comment by MiguelMA3** [comment]
Entendi, vou dar uma analisada no seu código e tentar pegar uma base para o meu projeto.
Valeu, aí.
